### ISSUE TITLE
I have this feature in Firefox 89.0.2

### ISSUE THREAD

**Issue by kieranbarker** [remy/light-dark-switcher#1]
Hey Remy, awesome project! I'm a big fan of your work!

I just wanted to let you know that I have this feature in the stable version of Firefox 89.0.2:

<img width="270" alt="A screenshot showing the 'System theme' setting in Firefox 89.0.2." src="https://user-images.githubusercontent.com/29986418/123415335-041d0000-d5ad-11eb-9cd1-ca489356ddd8.png">

Hopefully you'll get it soon!

**Comment by remy** [comment]
No, that's a system theme that's fixed to a single dark and light theme. The system light theme, for me, is way too light, so I had to customise it (the toolbar was fading out of my sight), and as soon as you customise the theme it no longer switches in dark and light - hence why I made the plugin :)

**Comment by kieranbarker** [comment]
Ahhh, sorry about that, a misunderstanding on my part. Like I said, cool project! 🤩
